spring.application.name=EcomApp
spring.data.mongodb.database=ecom_app_db
spring.data.mongodb.uri=mongodb+srv://myuser:mypassword123@ecomapp.fovkcs3.mongodb.net/ecom_app_db?retryWrites=true&w=majority&appName=EcomApp
server.port=${PORT:8080}